config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
  # 名前は必須入力かつ20文字以内
  validates :name, length: { maximum: 20 }, presence: true
  # 内容は必須入力かつ2文字以上30文字以内
  validates :body, length: { minimum: 2, maximum: 30 }, presence: true

  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 150 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]

  def index
    @message = Message.new
    # Messageを全て取得する
    @messages = Message.all
  end

  def create
    @message = Message.new(message_params)
    if  @message.save
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      # メッセージが保存できなかったとき
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    redirect_to root_path , notice: 'メッセージを削除しました'
  end

  private
  def message_params
    params.require(:message).permit(:name, :body, :age)
  end

  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Message Board</a>
        </div>
      </div>
    </nav> <!-- navbar navbar-default -->

    <div class="container" id="contents">
      <div class="row">
      <% if notice %>
        <div class="alert alert-info">
          <%= notice %>
        </div>
      <% end %>

      <%= yield %>
      </div>
    </div><!-- container-->

    <footer>
      <div class="copyright">Message Board</div>
    </footer>

    <script type="text/javascript">
      (function($){
        $('div.alert-info').delay(2000).fadeOut(1500);
      })(jQuery);
    </script>

  </div> <!--  #wrap -->
</body>
</html>

app/views/messages/_form.html.erb
<div class="form-horizontal" role="form">
  <%= form_for @message do |f| %>
    <% if @message.errors.present? %>
      <div class="alert alert-danger">
        <%= alert %>
        <ul>
          <% @message.errors.full_messages.each do |full_message| %>
            <li>
              <%= full_message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <div class="row">
        <label for="InputName" class="col-sm-offset-3 col-sm-1 control-label text-right">名前</label>
        <div class="col-sm-8">
          <%= f.text_field :name, id: "InputName", class: "form-control form_naco", placeholder: "name" %>
        </div>
      </div> <!-- row -->
    </div> <!-- form-group -->

    <div class="form-group">
      <div class="row">
        <label for="InputComment" class="col-sm-offset-3 col-sm-1 control-label text-right">内容</label>
        <div class="col-sm-8">
          <%= f.text_area :body, id: "InputComment", class: "form-control form_naco", cols: 10, rows: 5, placeholder: "comment"%>
        </div>
      </div> <!-- row -->
    </div> <!-- form-group -->

    <div class="form-group">
      <div class="row">
        <label for="InputAge" class="col-sm-offset-3 col-sm-1 control-label text-right">年齢</label>
        <div class="col-sm-8">
          <%= f.number_field :age, id: "InputAge", class: "form-control form_age", min: "0", max: "150" %>
        </div>
      </div> <!-- row -->
    </div> <!-- form-group -->

    <div class="form-group sub_btn">
      <div class="row">
        <div class="col-sm-offset-6 col-sm-6">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      </div> <!-- row -->
    </div> <!-- form-group sub_btn-->
  <% end %>
</div> <!-- form-horizontal -->

app/views/messages/edit.html.erb
<h2 class="edit_h2">メッセージの編集</h2>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="panel">
  <div class="panel-heading">
    <h4>メッセージ一覧</h4>
  </div>


  <div class="panel-body">
    <% @messages.each do |message| %>
    <div class="line_height">
      <span class="label label-info"><%= message.name %></span><span class="age">（年齢：<%= message.age %>）</span>：
      <%= message.body %>
        <span class="pull-right">
          <span class="btn btn-default btn-sm">
            <%= link_to "edit", edit_message_path(message), class: "btn_edit"%>
          </span>
          <span class="btn btn-default btn-sm">
            <%= link_to "destroy", message, method: :delete, data: { confirm: '削除してもよろしいですか？' }, class: "btn_destroy"%>
          </span>
        </span>
      <br>
    </div> <!-- line_height -->
    <% end %>
  </div> <!-- panel-body -->
</div> <!-- panel -->

<%= render 'form' %>